version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USR}
      POSTGRES_PASSWORD: ${DB_PWD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_URL: ${DB_URL}
      DB_USR: ${DB_USR}
      DB_PWD: ${DB_PWD}
      ENCRYPTION_SECRET: ${ENCRYPTION_SECRET}
      ENCRYPTION_ALGORITHM: ${ENCRYPTION_ALGORITHM}
    ports:
      - "8080:8080"

volumes:
  pgdata:
